# Generated by Django 3.2.6 on 2022-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('TableId', models.AutoField(primary_key=True, serialize=False)),
                ('TabelName', models.CharField(max_length=500)),
                ('PlayerIn', models.BigIntegerField()),
            ],
        ),
    ]
