# Generated by Django 3.1 on 2022-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('TableId', models.AutoField(primary_key=True, serialize=False)),
                ('TableName', models.CharField(max_length=500)),
                ('PlayerIn', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tabel',
        ),
    ]
